
    - name: Ensure mongo-compose directory exists
      file:
        path: /opt/mongodb-stack
        state: directory

    - name: Copy Docker Compose template
      template:
        src: mongo-compose.yml
        dest: /opt/mongodb-stack/docker-compose.yml

    - name: Deploy with docker_compose module
      community.docker.docker_compose:
        project_src: /opt/mongodb-stack
        state: present
