
- name: Create Monitoring directory
  file:
    path: /opt/monitoring-stack
    state: directory

- name: Deploy Docker Compose file
  template:
    src: monitoring-compose.yml
    dest: /opt/monitoring-stack/docker-compose.yml

- name: Deploy Docker Compose file
  template:
    src: prometheus.yml
    dest: /opt/monitoring-stack/prometheus.yml

- name: Start Monitoring Services
  command: docker compose up -d
  args:
    chdir: /opt/monitoring-stack
