name: VPS Provision Pipeline.

on:
  push:
    branches:
      - main

jobs:
  provision-vps-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ansible & Docker Python dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible docker

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: provision/playbook.yml
          inventory: "${{ secrets.VPS_HOST }}"
          options: >
            --extra-vars "ansible_user=${{ secrets.VPS_USERNAME }} ansible_password=${{ secrets.VPS_PASSWORD }} ansible_become=yes ansible_python_interpreter=/usr/bin/python3.12"
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
